services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crusty-cache-dev
    volumes:
      - .:/home/eduardo/crusty-cache
    ports:
      - "2222:22"
    working_dir: /home/eduardo/crusty-cache
    stdin_open: true
    tty: true
