[package]
name = "memory"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono ={ workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
